name: deploying websocket server

on:
  push:
    branches:
      - main

jobs:
  build:  
    runs-on:  ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to the dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_PASSWORD  }}

      - name: build and push the image
        uses: docker/build-push-action@v5
        with:
          context:  .
          file: ./Docker/ws.dockerfile
          build-args: |
            DATABASE_URL=${{secrets.DATABASE_URL}}
          push: true
          tags: mohitprasad004/ws-demo:${{github.sha}}

      - name: Deploy to server via SSH
        run:  |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 700 ~/ssh_key

          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" &> ~/.ssh/known_hosts

          ssh -i ~/ssh_key ubuntu@${{ secrets.SERVER_HOST }} -o StrictHostKeyChecking=no << 'EOF'
            docker rm -f user_ws || true
            docker pull mohitprasad004/ws-demo:${{ github.sha }}
            docker run --name user_ws -d -p 3000:3000 \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              mohitprasad004/ws-demo:${{ github.sha }}

            docker image prune -af
          EOF