name: deploying websocket server

on:
  push:
    branches:
      - main

jobs:
  build:  
    runs-on:  ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to the dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_PASSWORD  }}

      - name: build and push the image
        uses: docker/build-push-action@v5
        with:
          context:  .
          file: ./Docker/ws.dockerfile
          build-args: |
            DATABASE_URL=${{secrets.DATABASE_URL}}
          push: true
          tags: mohitprasad004/ws-demo:${{github.sha}}